pass more info in wasm_on_header_complete
nodejs/llhttp pull request #116
Opened 2021-06-08 07:54 UTC by ronag

Avoids the need for additional calls into wasm.

2021-06-09 06:29 UTC, indutny requested changes
Left few suggestions, otherwise LGTM.

2021-06-09 06:29 UTC, indutny commented on src/native/api.c
> +{
```suggestion
static int wasm_on_headers_complete_wrap(llhttp_t * p) {
```

2021-06-09 06:29 UTC, indutny commented on src/native/api.c
> +  on_headers_complete,
```suggestion
  wasm_on_headers_complete_wrap,
```

2021-06-13 05:25 UTC, indutny commented
Landed with minor style changes in 5b0d030 . Thanks!

2021-06-13 05:25 UTC, closed without merging

2021-06-13 05:25 UTC, indutny commented
Would a patch release be sufficient, or would you prefer a minor release?

2021-06-13 09:17 UTC, ronag commented
Patch is ok for me

2021-06-13 20:06 UTC, indutny commented
Done! v6.0.3 is the release that has this.