fix: Reset Content-length upon reset.
nodejs/llhttp pull request #203
Opened 2022-10-07 19:58 UTC by ShogunPanda

Fixes #202.

2022-10-08 06:37 UTC, mcollina requested changes

2022-10-08 06:37 UTC, mcollina commented on test/request/content-length.md
> +## Content-Length reset when no body is assumed
```suggestion
## Content-Length reset when no body is received
```

2022-10-08 06:37 UTC, mcollina commented on test/response/content-length.md
> +## Content-Length reset when no body is assumed
```suggestion
## Content-Length reset when no body is received
```

2022-10-11 04:55 UTC, ronag approved these changes

2022-10-11 08:22 UTC, merged